#+TITLE:   emacs/vterm
#+DATE:    January 16, 2019
#+SINCE:   {replace with next tagged release version}
#+STARTUP: inlineimages

* Table of Contents :TOC_3:noexport:
- [[Description][Description]]
  - [[Known bugs][Known bugs]]
  - [[Module Flags][Module Flags]]
  - [[Plugins][Plugins]]
  - [[Hacks][Hacks]]
- [[Prerequisites][Prerequisites]]
- [[Features][Features]]
- [[Configuration][Configuration]]
- [[Troubleshooting][Troubleshooting]]

* Description
a emacs-libvterm module

FIXME: currently working in progress.

** Known bugs
- Does not automaticaly go to insert mode when use evil.
- Does not automaticaly kill the buffer or switch to normal mode when terminal ends.
- =C-d= cannot be used inside the terminal.
- The =+vterm/open-popup= function does not working. It is now functions the
  same as =+vterm/open=.

** Module Flags
This module provides no flags.

** Plugins

** Hacks

* Prerequisites

You have to compile emacs with =--with-modules= option.

Lookat the =system-configuration-options= variable to see if your emacs has this option.

You need to have =libvterm= installed in your system.

On Ubuntu or Debian:

#+BEGIN_SRC sh
sudo apt install libvterm-dev
#+END_SRC

On ArchLinux or Manjaro:

#+BEGIN_SRC sh
sudo pacman -S libvterm
#+END_SRC

On macOS:

#+BEGIN_SRC sh
brew install libvterm
#+END_SRC

You also need to have =make= =cmake= and a c compiler in your system to compile libvterm-module.

* Features

* Configuration

* Troubleshooting
