# All SpaceVim option below [option] section
[options]
  enable_googlesuggest = true
  enable_statusline_mode = true
  max_column = 80
  guifont = 'SauceCodePro Nerd Font:h12'
  relativenumber = false
  statusline_separator = 'arrow'
  enable_key_frequency = true
  enable_cursorcolumn = false
  enable_tabline_filetype_icon = true
  enable_os_fileformat_icon = true
  github_username = 'SteamedFish'
  enable_vimfiler_gitstatus = true
  enable_vimfile_filetypeicon = true

[[layers]]
  name = "VersionControl"
[[layers]]
  name = "autocomplete"
[[layers]]
  name = "chat"
[[layers]]
  name = "checkers"
  lint_on_the_fly = true
[[layers]]
  name = "colorscheme"
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
[[layers]]
  name = "cscope"
[[layers]]
  name = "debug"
[[layers]]
  name = "default"
[[layers]]
  name = "git"
[[layers]]
  name = "github"
[[layers]]
  name = "lang#go"
[[layers]]
  name = "lang#html"
[[layers]]
  name = "lang#javascript"
[[layers]]
  name = "lang#markdown"
[[layers]]
  name = "lang#php"
[[layers]]
  name = "lang#python"
[[layers]]
  name = "lang#vim"
[[layers]]
  name = "shell"
  default_position = 'bottom'
[[layers]]
  name = "tags"
[[layers]]
  name = "tools"
[[layers]]
  name = "tools#dash"
[[layers]]
  name = "ui"
[[layers]]
  name = "denite"
