(global-git-commit-mode t)
(setq powerline-default-separator 'arrow)
(spacemacs/toggle-transparency)
(spacemacs//set-monospaced-font "Source Code Pro" "Hiragino Sans GB" 13 16)
(setq pangu-spacing-real-insert-separtor t)
(server-start)
