---
- name: 安装 Emacs
  block:
      - name: 配置 emacs-mac 的 tap
        homebrew_tap:
            name: railwaycat/emacsmacport
            state: present
      - name: 配置 emacs-mac 的 osx-defaults
        when: ansible_distribution == "MacOSX"
        block:
            - osx_defaults:
                domain: org.gnu.Emacs
                key: Emacs.ToolBar
                value: "no"
            - osx_defaults:
                domain: org.gnu.Emacs
                key: Emacs.ScrollBar
                value: "no"
            - osx_defaults:
                domain: org.gnu.Emacs
                key: Emacs.MenuBar
                value: "no"

- name: 安装 Emacs 所依赖的各种工具
  block:
      - name: 配置 ccls 的 tap
        when: ansible_distribution == "MacOSX"
        homebrew_tap:
            name: twlz0ne/ccls
            state: present
