---
- name: 配置 emacs-mac 的 osx-defaults
  when: ansible_distribution == "MacOSX"
  block:
      - osx_defaults:
          domain: org.gnu.Emacs
          key: Emacs.ToolBar
          value: "no"
      - osx_defaults:
          domain: org.gnu.Emacs
          key: Emacs.ScrollBar
          value: "no"
      - osx_defaults:
          domain: org.gnu.Emacs
          key: Emacs.MenuBar
          value: "no"
